# Generated by Django 5.0.6 on 2024-05-10 20:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_creation_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('grade', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'grade')},
        ),
    ]
