version: "3.8"

services:
  database:
    container_name: devpro_database
    image: postgres:16.1
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=devpro
      - POSTGRES_USER=devpro
    ports:
      - 5434:5432
