# Generated by Django 5.0.4 on 2024-04-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vimeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('vimeo_id', models.CharField(max_length=96)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
