# Generated by Django 5.0.4 on 2024-05-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('public', models.TextField(max_length=128)),
                ('description', models.TextField(max_length=512)),
            ],
        ),
    ]
