# Generated by Django 5.0.4 on 2024-05-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=64)),
                ('public', models.TextField(max_length=128)),
                ('description', models.TextField(max_length=512)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
