# Generated by Django 5.0.6 on 2024-05-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_lesson_vimeo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='vimeo_id',
            field=models.CharField(max_length=32),
        ),
    ]
